"""create_ocr_documents_table

Revision ID: 7af5f5f0d67a
Revises: ded6986943bd
Create Date: 2026-09-30 03:53:55.010901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af5f5f0d67a'
down_revision: Union[str, Sequence[str], None] = 'ded6986943bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_documents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fund_request_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('ocr_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ocrstatus'), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_other_party_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('extracted_date', sa.Date(), nullable=True),
    sa.Column('ocr_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_ocr_documents_fund_request_id'), 'ocr_documents', ['fund_request_id'], unique=False)
    op.create_index(op.f('ix_ocr_documents_ocr_status'), 'ocr_documents', ['ocr_status'], unique=False)
    op.create_index(op.f('ix_ocr_documents_user_id'), 'ocr_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_documents_user_id'), table_name='ocr_documents')
    op.drop_index(op.f('ix_ocr_documents_ocr_status'), table_name='ocr_documents')
    op.drop_index(op.f('ix_ocr_documents_fund_request_id'), table_name='ocr_documents')
    op.drop_table('ocr_documents')
    # ### end Alembic commands ###
