"""create initial tables

Revision ID: ded6986943bd
Revises: 
Create Date: 2026-09-29 06:16:41.785536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded6986943bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EMPLOYEE', name='userrole'), nullable=True),
    sa.Column('employer_id', sa.Uuid(), nullable=True),
    sa.Column('fund_account_type', sa.String(length=30), nullable=True),
    sa.Column('employees_managed', sa.Integer(), nullable=True),
    sa.Column('invite_code_hash', sa.String(length=64), nullable=True),
    sa.Column('invite_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code_hash')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employer_id'), 'users', ['employer_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('pockets',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('allocated_amount > 0', name='ck_pocket_allocated_amount_positive'),
    sa.CheckConstraint('remaining_amount <= allocated_amount', name='ck_pocket_remaining_not_exceed_allocated'),
    sa.CheckConstraint('remaining_amount >= 0', name='ck_pocket_remaining_amount_non_negative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pockets_owner_id'), 'pockets', ['owner_id'], unique=False)
    op.create_table('cards',
    sa.Column('pocket_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_four_digits', sa.String(length=4), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('spent', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NONACTIVE', name='cardstatus'), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_card_balance_non_negative'),
    sa.CheckConstraint('expiry_month >= 1 AND expiry_month <= 12', name='ck_card_expiry_month'),
    sa.CheckConstraint('spent >= 0', name='ck_card_spent_non_negative'),
    sa.ForeignKeyConstraint(['pocket_id'], ['pockets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_pocket_id'), 'cards', ['pocket_id'], unique=False)
    op.create_table('pocket_access',
    sa.Column('pocket_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pocket_id'], ['pockets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pocket_id', 'employee_id', name='uq_pocket_employee_access')
    )
    op.create_index(op.f('ix_pocket_access_employee_id'), 'pocket_access', ['employee_id'], unique=False)
    op.create_index(op.f('ix_pocket_access_pocket_id'), 'pocket_access', ['pocket_id'], unique=False)
    op.create_table('card_access',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'employee_id', name='uq_card_employee_access')
    )
    op.create_index(op.f('ix_card_access_card_id'), 'card_access', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_access_employee_id'), 'card_access', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_access_employee_id'), table_name='card_access')
    op.drop_index(op.f('ix_card_access_card_id'), table_name='card_access')
    op.drop_table('card_access')
    op.drop_index(op.f('ix_pocket_access_pocket_id'), table_name='pocket_access')
    op.drop_index(op.f('ix_pocket_access_employee_id'), table_name='pocket_access')
    op.drop_table('pocket_access')
    op.drop_index(op.f('ix_cards_pocket_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_pockets_owner_id'), table_name='pockets')
    op.drop_table('pockets')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_employer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
